---
title: "DEG analysis using MAST"
output:
  html_document:
    df_print: paged
---


```{r}
library(Seurat)
library(ggplot2)
library(plyr)
```

```{r}
setwd('../')
dir.create('res_various/res_0.3/')
dir.create('res_various/res_0.3/degs_mast/')
```

```{r}
subdataset <- readRDS('tmp/crc_smc.malignantcells.Rds')
head(subdataset@meta.data, n=3); nrow(subdataset@meta.data) # 17334

```

```{r}
subdataset@meta.data <- subdataset@meta.data[, c(1:6,10)]
head(subdataset@meta.data, n=3)
```

```{r}
summary(subdataset$RNA_snn_res.0.3)
```

```{r}
Idents(subdataset) <- 'RNA_snn_res.0.3'
markers_mast <- FindAllMarkers(object = subdataset, min.pct = 0.25, logfc.threshold = 0.25, only.pos = T, test.use = 'MAST'); nrow(markers_mast) # 1314

markers_mast <- subset(markers_mast, p_val_adj <= 0.05); nrow(markers_mast) # 1286
markers_mast$Symbol <- unlist(lapply(markers_mast$gene, function(x) unlist(strsplit(x, split = '-ENSG'))[1]))
head(markers_mast, n=3)

write.table(markers_mast, 'res_various/res_0.3/degs_mast/markers.MAST.txt', sep = '\t', quote = F, col.names = T, row.names = F) 
saveRDS(subdataset, 'tmp/crc_smc.malignantcells.Rds')
```


